# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

name: Setup Environment
description: setup environment to build/test/lint rust applications
inputs:
  toolchain:
    description: 'Rust toolchain to use'
    required: false
    default: 'stable'
  workspace:
    description: 'Cargo workspace to cache'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      id: setup-rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustc, clippy, rustfmt
        rustflags: ""
        cache-workspaces: ${{ inputs.workspace }}
        cache-on-failure: false
        cache-shared-key: ${{runner.os}}-rust-${{hashFiles('**/Cargo.lock')}}
        cache-all-crates: trus

    - name: Setup Taskfile
      uses: ./.github/actions/setup-task
      with:
        version: latest
        cache-enabled: true

    - name: Install C/C++ toolchain
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        curl -L https://apt.llvm.org/llvm.sh -o /tmp/llvm.sh
        chmod +x /tmp/llvm.sh
        sudo /tmp/llvm.sh 19
        sudo apt-get install -y \
          pkg-config \
          make \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          gcc-x86-64-linux-gnu \
          g++-x86-64-linux-gnu
