# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

vars:
  CARGO_COMPONENTS: "cargo-sort cargo-audit cargo-llvm-cov cargo-machete@0.7.0 cargo-deny@0.17.0 typos-cli"

tasks:
  test:run-mcp-server:
    desc: run mcp server using SSE transport
    cmds:
      - |
        cd examples/mcp-server/
        uv run main.py --port 8000

  run-mcp-proxy:
    desc: run mcp proxy
    cmds:
      - cargo run -- --config config/mcp-proxy-config.yaml --svc-name slim/0 --name org/mcp/proxy --mcp-server http://localhost:8000/sse

  test:run-mcp-client:
    desc: run a simple MCP client that use SLIM as transport protocol
    cmds:
      - |
        cd examples/mcp-slim-client
        uv run main.py

  test:reinstall-and-run-mcp-client:
    desc: run a simple MCP client that use SLIM as transport protocol
    cmds:
      - |
        cd examples/mcp-slim-client
        uv run --reinstall main.py

  run-slim:
    desc: run an SLIM node
    cmds:
      - |
        cd ../../../
        cargo run --bin slim -- --config config/base/server-config.yaml

  example:run-mcp-server-time-sse:
    desc: run mcp server time using SSE transport using New York time
    cmds:
      - |
        uvx --from slim-mcp mcp-server-time --local-timezone "America/New_York" --transport sse

  example:run-mcp-server-time-slim:
    desc: run mcp server time using SSE transport using New York time
    cmds:
      - |
        uvx --from slim-mcp mcp-server-time --local-timezone "America/New_York" --transport slim

  example:run-llamaindex-time-agent-proxy:
    desc: run llama index time agent
    cmds:
      - |
        uvx --from slim-mcp llamaindex-time-agent --city "New York" --mcp-server-organization "org" --mcp-server-namespace "mcp" --mcp-server-name "proxy"

  example:run-llamaindex-time-agent:
    desc: run llama index time agent
    cmds:
      - |
        uvx --from slim-mcp llamaindex-time-agent --city "New York"

  build:strip:
    desc: "Build the project and strip the debug symbols"
    cmds:
      - task: :build
      - task: :toolchain:strip
        vars:
          TARGET_BIN: "target/{{.TARGET}}/{{.PROFILE}}/slim-mcp-proxy"
