apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-proxy.fullname" . }}-config
  labels:
    {{- include "mcp-proxy.labels" . | nindent 4 }}
data:
  mcp-proxy-config.yaml: |
    tracing:
      log_level: {{ .Values.proxy.slim.tracing.logLevel }}
      display_thread_names: {{ .Values.proxy.slim.tracing.displayThreadNames }}
      display_thread_ids: {{ .Values.proxy.slim.tracing.displayThreadIds }}
    
    runtime:
      n_cores: {{ .Values.proxy.slim.runtime.nCores }}
      thread_name: {{ .Values.proxy.slim.runtime.threadName | quote }}
      drain_timeout: {{ .Values.proxy.slim.runtime.drainTimeout }}
    
    services:
      {{ .Values.proxy.slim.serviceName }}:
        dataplane:
          clients:
            - endpoint: {{ .Values.proxy.slim.server.endpoint | quote }}
              tls:
                insecure: {{ .Values.proxy.slim.server.tls.insecure }}
