# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-helm

on:
  push:
    tags:
      - 'helm-*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  prepare-build:
    name: Prepare Build
    permissions:
      contents: read
    outputs:
      release_tag: ${{ steps.resolve.outputs.release_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Resolve release tag
        id: resolve
        run: |
          tag="${GITHUB_REF#refs/*/}"; echo "release_tag=${tag#helm-}" >> "$GITHUB_OUTPUT"

  release:
    name: Release Helm charts
    needs: [ prepare-build ]
    if: ${{ needs.prepare-build.outputs.release_tag != '' }}
    uses: ./.github/workflows/reusable-helm-release.yaml
    permissions:
      contents: 'read'
      packages: 'write'
      attestations: 'write'
    with:
      registry: ghcr.io/agntcy/slim-mcp-rust
      release_tag: ${{ needs.prepare-build.outputs.release_tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}