# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: reusable-lint-test-helm-chart

on:
  workflow_call:
    inputs:
      chart-path:
        description: "Path to the chart to lint"
        required: true
        type: string
      config-file:
        description: "Path to the chart-testing config file"
        required: false
        type: string
        default: ""
      dependencies:
        description: "List of dependencies to add"
        required: false
        default: ""
        type: string


jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: "true"

      - name: Print chart path
        env:
          CHART_PATH: ${{ inputs.chart-path }}
        run: |
          echo "Chart path: $CHART_PATH"

      - name: Setup K8s
        uses: ./.github/actions/setup-k8s
        with:
          kind-create-cluster: true

      - name: Add dependencies
        shell: bash
        env:
          DEPENDENCIES: ${{ inputs.dependencies }}
        run: |
          IFS=$'\n' readarray -t dependencies <<< "$DEPENDENCIES"
          for dependency in "${dependencies[@]}"; do
            # Skip line if it is empty
            if [[ -z "${dependency//[[:space:]]/}" ]]; then
              continue
            fi

            # Split the dependency into name and repo
            IFS='@' read -r name repo <<< "${dependency}"

            echo helm repo add "${name}" "${repo}"
          done

      - name: Run chart-testing (lint & test)
        env:
          TARGET_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
          CHART_PATH: ${{ inputs.chart-path }}
          CONFIG_FILE: ${{ inputs.config-file }}
        run: |
          args=(
            --debug
            --target-branch="$TARGET_BRANCH"
            --chart-dirs "$CHART_PATH"
            --validate-maintainers=false
            --check-version-increment=false
          )

          if [[ -f "$CONFIG_FILE" ]]; then
            args+=("--config $CONFIG_FILE")
          fi

          ct lint-and-install "${args[@]}"