# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: reusable-helm-release

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
        description: "OCI registry to use."
      release_tag:
        required: true
        type: string
        description: "Release tag for all components."
      helm-version:
        required: false
        default: "3.12.1"
        type: string
        description: 'Helm version'
    secrets:
      github-token:
        description: "github token"
        required: true

jobs:
  chart:
    name: Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.github-token}}

      - name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: ${{ inputs.helm-version }}

      - name: Set chart name
        id: chart-name
        shell: bash
        env:
          RELEASE_TAG: ${{ inputs.release_tag }}
        run: |
          echo "Resolving chart name from release tag: $RELEASE_TAG"
          _chart_name=$RELEASE_TAG

          # Extract the chart name from the release tag
          echo "value=${_chart_name%-v*}" >> "$GITHUB_OUTPUT"

          # extract the chart version form the tag
          echo "version=v${_chart_name##*-v}" >> "$GITHUB_OUTPUT"


      - name: Helm lint
        shell: bash
        env:
          CHART_NAME: ${{ steps.chart-name.outputs.value }}
        run: |
          ## By convention the name of the chart is the name of the folder under charts/
          helm lint "charts/$CHART_NAME" --with-subcharts

      - name: Helm package
        id: build
        shell: bash
        env:
          CHART_NAME: ${{ steps.chart-name.outputs.value }}
          CHART_VERSION: ${{ steps.chart-name.outputs.version }}
        run: |
          helm package "charts/$CHART_NAME" --dependency-update --version "$CHART_VERSION"
          echo "package=${CHART_NAME}-${CHART_VERSION}.tgz" >> "$GITHUB_OUTPUT"

      - name: Helm push to GHCR OCI registry
        shell: bash
        env:
          HELM_PACKAGE: ${{ steps.build.outputs.package }}
          REGISTRY: ${{ inputs.registry }}
        run: |
          echo "🚧 Pushing $HELM_PACKAGE to GHCR OCI registry"
          helm push "$HELM_PACKAGE" "oci://$REGISTRY/helm"